backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"

publish_mode: simple

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "tshirts"
    label: "T-Shirts"
    folder: "content/tshirts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - label: "Available Sizes"
        name: "sizes"
        widget: "list"
        default: ["S", "M", "L", "XL", "XXL"]
      - { label: "Image", name: "image", widget: "image" }
      - { label: "In Stock", name: "in_stock", widget: "boolean", default: true }
